name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
      - name: Set PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('poetry.lock') }}-${ GITHUB_REF }
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      # - name: Install inference dependencies
      #   run: |
      #     curl -sSL https://install.python-poetry.org | python - --version 1.8.3
      #     poetry install --no-root --without dev

      # - name: Run inference tests
      #   run: |
      #     poetry run pytest -s lantern --ignore lantern/early_stopping.py

      - name: Install all dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python - --version 1.8.3
          poetry install --no-root -E train

      - name: Run all tests
        run: |
          poetry run pytest -s

      - name: Lint
        run: |
          poetry run ruff check .

      - name: Build wheels
        run: |
          poetry build
